// THIRD PARTY IMPORTS
import { Typography } from '@mui/material'
import { Box } from '@mui/system'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useRef, useState } from 'react'
import { motion } from 'framer-motion'

import ThreeComponent from '../components/ThreeComponent'
import PageSwapMotion from '../components/PageSwapMotion'
import styles from '../styles/Home.module.scss'
import { FONT_SIZES } from '../constants/fontsSize'

const Home: NextPage = () => {
    const textRef = useRef<HTMLHeadingElement>(null)

    return (
        <PageSwapMotion>
            <Box
                sx={{
                    height: `100vh`,
                    width: `100vw`,
                    overflowY: `hidden`,
                    scrollBarWidth: 'none',
                }}
            >
                <Head>
                    <title>Aman Kumar</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Box
                    sx={{
                        height: `100vh`,
                        display: `flex`,
                        zIndex: 5,
                        justifyContent: `center`,
                        alignItems: `center`,
                        flexDirection: `column`,
                        overflow: `hidden`,
                    }}
                >
                    <ThreeComponent />
                    <Box
                        sx={{
                            flex: 1,
                            display: 'flex',
                            justifyContent: 'flex-start',
                            alignItems: 'center',
                            flexDirection: 'column',
                            padding: '20px',
                        }}
                    >
                        <Typography
                            variant="h2"
                            sx={{
                                fontSize: {
                                    lg: FONT_SIZES.index.h2.lg,
                                    md: FONT_SIZES.index.h2.md,
                                    xs: FONT_SIZES.index.h2.xs,
                                },
                            }}
                        >
                            Hi There
                        </Typography>
                        <Typography
                            variant="h1"
                            sx={{
                                fontSize: {
                                    lg: FONT_SIZES.index.h1.lg,
                                    md: FONT_SIZES.index.h1.md,
                                    xs: FONT_SIZES.index.h1.xs,
                                },
                            }}
                        >
                            I'm Aman Kumar
                        </Typography>
                        <Typography
                            variant="h2"
                            sx={{
                                fontSize: {
                                    lg: FONT_SIZES.index.h2.lg,
                                    md: FONT_SIZES.index.h2.md,
                                    xs: FONT_SIZES.index.h2.xs,
                                },
                                marginTop: 1,
                            }}
                        >
                            Full Stack Web Developer
                        </Typography>
                        <Typography
                            component="p"
                            sx={{
                                textAlign: 'center',
                                fontSize: {
                                    lg: FONT_SIZES.index.pFont.lg,
                                    md: FONT_SIZES.index.pFont.md,
                                    xs: FONT_SIZES.index.pFont.xs,
                                },
                                marginTop: 2,
                            }}
                        >
                            A computer enthusiast who loves creating websites
                            and exploring emerging web technologies.
                        </Typography>
                        {/* <h1 ref={textRef}></h1> */}
                    </Box>
                </Box>
            </Box>
        </PageSwapMotion>
    )
}

export default Home
